/*
    O bloco try catch vai tentar executar um código, caso não consiga ele pode retornar o erro que esse código gerou.
    Diferente das exceptions, ele não para o código.
*/

try {

    let a = 2 + b;

} catch (error) {

    console.log(error);

}